# Generated by Django 2.1.4 on 2018-12-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_child', to='api.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_parent', to='api.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='reference_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
