# Generated by Django 2.1.4 on 2018-12-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181222_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topics', 'verbose_name_plural': 'Topics'},
        ),
    ]
