# Generated by Django 2.1.4 on 2018-12-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181222_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='child',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='reference_id',
        ),
    ]
