# Generated by Django 2.1.4 on 2018-12-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181223_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=256)),
            ],
        ),
    ]
