# Generated by Django 2.1.4 on 2018-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_topiclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ref_id',
            field=models.IntegerField(default=0),
        ),
    ]
